### ISSUE TITLE
Cannot install squib on Mac

### ISSUE THREAD

**Issue by titib** [andymeneely/squib#279] opened 2019-06-26 07:50 UTC
Hello,

I tried to install squib on my mac without success. Can you help me to figure out what was wrong. Thank you.

`PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig sudo gem install squib`

The errors are : 

```
Building native extensions.  This could take a while...
ERROR:  Error installing squib:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/cairo-1.15.13/ext/cairo
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20190626-13731-1j98jvf.rb extconf.rb
checking for GCC... yes
checking for Win32 OS... no
checking for cairo version (>= 1.2.0)... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/$(RUBY_BASE_NAME)
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:319:in 'parse_pc': .pc for libffi doesn't exist. (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:218:in 'declaration'
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:232:in 'collect_cflags'
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:167:in 'cflags'
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:234:in 'block in collect_cflags'
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:233:in 'collect'
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:233:in 'collect_cflags'
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:167:in 'cflags'
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:234:in 'block in collect_cflags'
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:233:in 'collect'
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:233:in 'collect_cflags'
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:176:in 'cflags_only_other'
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:496:in 'cflags_only_other'
	from /Library/Ruby/Gems/2.3.0/gems/pkg-config-1.3.7/lib/pkg-config.rb:543:in 'have_package'
	from extconf.rb:52:in 'required_pkg_config_package'
	from extconf.rb:60:in '<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/cairo-1.15.13/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/cairo-1.15.13 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/cairo-1.15.13/gem_make.out

```

My environment :
- ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
- MacOS Mojave 10.14.5

**Comment by jeromecance** [comment] 2019-09-26 09:55
I can't instal it too. It seems very promising so it's quite disappointing to not being able to install it.

I got the same weird `/usr/local/opt/libffi/lib/pkgconfig/libffi.pc doesn't exist` even if the file really exists. I also added `PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig` to my bash_profile without success. 

I don't know what to do. Any workaround?

- macOS 10.14.6.
- Ruby 2.4.7

**Comment by andymeneely** [comment] 2019-09-26 16:09
Bummer that this isn't working for you! Usually these things work easier on macs. Here's some ideas.

# My mac environment

So my Mac environment is also macOS 10.14.6, with rbenv 1.1.2. I had Ruby 2.5.1 but for this I started clean and did Ruby 2.5.6.

There *shouldn't* be a reason that Ruby 2.4 wouldn't work, but it does work on 2.5 for me. Let's try changing to ruby 2.5.6:

```
$ rbenv install 2.5.6
$ rbenv global 2.5.6
$ gem install squib
```
Then I get lots of messages from the gem install.

I did not have to do anything pkgconfig. 

@jeromecance and @titib Are you using homebrew? I have homebrew installed and I periodically do `brew update`.  

## Docker

Yeah so I'm still experimenting with the best way to use Docker, and I haven't documented my work just yet. The way I have it working for me is that your current directory (the one you do `docker run` from) will map to the `/usr/src/app` directory within the image. When squib-in-docker read & writes files from there, it'll write it back out to your current directory. 

Assuming you have this hello world script in the current directory called `hello.rb`:

```ruby
require 'squib'

Squib::Deck.new do
  background color: :white
  text str: 'Hello, World!'
  save_png
end
```

Then you run (this is assuming Windows...)

```
docker run --rm -v "%cd%":/usr/src/app andymeneely/squib ruby hello.rb
```
For macs you would do this:

```
docker run --rm -v "$PWD":/usr/src/app andymeneely/squib ruby hello.rb
```
Then I get this output
```
WARNING: Nokogiri was built against LibXML version 2.9.8, but has dynamically loaded 2.9.4
2019-09-26 16:04:11 +0000 WARN: Dir '_output' does not exist, creating it.
```
The nokogiri warning I'm working on, but it doesn't seem to break anything.
Then `_output/card_00.png` is created in my local directory.

That `docker run` command is long and hard to remember. Sometimes I'll put it in its own batch and/or shell file. You can also do other things like make your own image based on the squib image and install things like different fonts or other tools. I do that here: https://github.com/andymeneely/project-timber-wolf/blob/master/Dockerfile

**Comment by titib** [comment] 2019-09-26 23:50
Unfortunately, I still have the same error even by following your suggestions.

I've just tried :
- brew update
- brew install rbenv
- rbenv init
- rbenv install 2.5.6
- rbenv global 2.5.6
- gem install squib

**Comment by jeromecance** [comment] 2019-09-27 05:51
Same here

**Comment by mgrecar** [comment] 2019-09-27 20:51
I also have the same problem.  I found [this issue](https://github.com/ruby-gnome/pkg-config/issues/18) with the `pkg-config` gem, and if I apply the changes that guy proposed (manually editing them my copy of that file, since that PR hasn't yet been merged yet), I do get past this particular issue.  So, in short, until `pkg-config` makes that update and releases `1.3.9`, I think using Docker is the only solution :(

**Comment by andymeneely** [comment] 2019-09-27 21:07
Looks like the pkg-config gem had an issue with homebrew. https://github.com/ruby-gnome/pkg-config/issues/18

I'll be cutting a new version of Squib tonight. (Still can't figure out why it WORKS for me...)

**Comment by andymeneely** [comment] 2019-09-27 23:46
Looks like the 1.3.9 of pkg-config is out now. Don't think there needs to be a new version of squib for it - just do `gem install pkg-config` and get the latest version, and remove any other versions.

**Comment by mgrecar** [comment] 2019-09-28 02:02
I can confirm it worked for me, was able to execute a simple example and it generated output with no error.  Thanks!

**Comment by titib** [comment] 2019-09-28 07:47
Now, it works !
But I had to install manually pango, librsvg and gdk-pixbuf with brew before installing squib. If I don't do it, I'd have compilation errors.

@mgrecar, @andymeneely  Thank you for your help.

**Closed** 2019-10-01 20:27 UTC
