### ISSUE TITLE
Images embedded in text are offset incorrectly when there is only 1 image and no text

### ISSUE THREAD

**Issue by programmingisgood** [andymeneely/squib#134] opened 2016-01-16 00:12 UTC
First, an image to show the issue:

![Image of problem](https://dl.dropboxusercontent.com/u/1651924/weird_squib_offset.png)

The top screenshot is a text field with an embedded icon. In the spreadsheet, it is simply: `(trash)`

The bottom screenshot is: `5 (gold) = (trash)`

So the image is offset when there is only 1 image in the text field.

The following "fixes" this issue: `(trash)(trash)` or `1(trash)`

Adding a space before or after the image doesn't help.

**Comment by andymeneely** [comment] 2016-01-16 15:19
Don't know what's happening here. The samples all place it in the expected place.

Plus, this example works with no problem:
```ruby
require 'squib'
require 'game_icons'

Squib::Deck.new(cards: 2) do
  text(str: ['(heart)', '1 (heart)']) do |embed|
    embed.svg key: '(heart)', width: 30, height: 30, data: GameIcons.get('glass-heart').string
  end
  save_png
end
```
Can you make a minimal example?

**Comment by programmingisgood** [comment] 2016-01-18 02:41
This reproduces the problem:

    require 'squib'
    puts Squib::VERSION

    dpi = 300
    iconSize = 52

    Squib::Deck.new(cards: 1, width: 1050, height: 750, dpi: dpi) do
        background color: :white

        x = 10
        y = 10
        rect x: x, y: y, width: 200, height: 60, radius: 0, stroke_color: "#000000", fill_color: "#DDDDDD", stroke_width: 4

        text(str: "test (trash)", x: x, y: y, width: 200, height: 60, markup: true,
             font: "Verdana, #{30}", color: "#000000", align: :left, valign: :middle) do |embed|
            embed.png key: '(trash)', width: iconSize, height: iconSize, dx: 0, dy: 0, file: 'art/trash_icon.png'
        end

        y += 100

        rect x: x, y: y, width: 200, height: 60, radius: 0, stroke_color: "#000000", fill_color: "#DDDDDD", stroke_width: 4

        text(str: "(trash)", x: x, y: y, width: 200, height: 60, markup: true,
             font: "Verdana, #{30}", color: "#000000", align: :left, valign: :middle) do |embed|
            embed.png key: '(trash)', width: iconSize, height: iconSize, dx: 0, dy: 0, file: 'art/trash_icon.png'
        end

        save_pdf file: 'test.pdf', width: 11 * dpi, height: 8.5 * dpi, margin: dpi * 0.45, gap: 1, trim: 0, rotate: true
    end`

![Image of Yaktocat](https://dl.dropboxusercontent.com/u/1651924/weird_squib_offset_2.png)

**Comment by andymeneely** [comment] 2016-01-18 21:56
I'll take a look, but I'm suspecting `valign: :middle` is the culprit. Is that absolutely necessary for this situation?

**Comment by programmingisgood** [comment] 2016-01-18 22:29
I can probably manually set the position instead of using valign but valign is very helpful.

**Comment by andjd** [comment] 2016-01-20 20:58
I suspect that valign is what's causing the issue, although the root of the problem is in how Squib calculates the extents of text— when there is no text rendered by pango and only embedded images, the height of the text extents is set to 0. When I record the extents of the text in your example, i get
```ruby
{:width=>142, :height=>48}
{:width=>52, :height=>0}
```

(note that the horizontal extents is still fine)

aside:  interestingly when at first I tried to just do `puts text ...` Squib just ignored the embed block whereas `a = text ... ; puts a` worked as expected.  Any idea why?

As a quick workaround, you can use `(trash) `.  Adding a space to the end of the string is enough to get the height extents to render properly.

**Comment by andymeneely** [comment] 2016-03-16 03:13
Should be fixed in the master branch now!

**Closed** 2016-03-16 03:12 UTC
Labels: bug

**Comment by programmingisgood** [comment] 2016-03-16 18:29
:D Thanks Andy!
