### ISSUE TITLE
save_sheet is adding 1px to the right for every 2 columns

### ISSUE THREAD

**Issue by mattparkes** [andymeneely/squib#185] opened 2016-11-20 01:49 UTC
(Using the current `dev` branch, at 300dpi)

As part of trying to work around #184 I'm trying to use save_sheet and then drop the files into Illustrator, with a cutting guide overlayed.
However the resultant output has an additional 1 pixel on the right hand side, for every 2 columns so when I set the image's size in illustrator to card_size * columns, it's out by a bit (3px for 6 cards wide)

This is easily demonstrated by doing:
`save_sheet` columns: 2, rows: 2 and opening the resulting file in an image editor, you'll note that the width will be (card_width *2) +1, or more telling, an odd number (not possible)

If you set your card's background color to red, you'll easily notice the extra white pixels.

**Comment by andymeneely** [comment] 2016-12-19 18:44
Hm, I can't reproduce this. What am I doing wrong? 

```ruby
require 'squib'

Squib::Deck.new cards: 5 do
  background color: :red
  save_sheet rows: 2, columns: 2, prefix: 'bug185_'
end
```

**Comment by andymeneely** [comment] 2017-10-06 15:55
Since I haven't been able to reproduce this, I'm closing it. If you have a code snippet I'd be happy to reopen.

**Closed by andymeneely** 2017-10-06 15:55 UTC
Labels: bug
