### ISSUE TITLE
Out of memory error when stroking text with embeds on Windows

### ISSUE THREAD

**Issue by pickfifteen** [andymeneely/squib#103] opened 2015-07-28 13:00 UTC
Adding a `stroke_width` to any text with any embeds in it, such as the example from `text_options.rb`, causes the following error. This error does not occur under Linux; I cannot test Mac currently. The text has to actually contain the embed; if the text is set up for embeds but none are actually contained in the string, it will work fine.

```
_cairo_win32_scaled_font_glyph_path: Cannot complete this function.
C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/cairo-1.14.1-x86-mingw32/lib/cairo/context/color.rb:7:in `set_source_rgba': out of memory (NoMemoryError)
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/gems/cairo-1.14.1-x86-mingw32/lib/cairo/context/color.rb:7:in `set_source_color'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/graphics/cairo_context_wrapper.rb:50:in `set_source_squibcolor'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/graphics/cairo_context_wrapper.rb:83:in `fancy_stroke'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/graphics/text.rb:108:in `stroke_outline!'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/graphics/text.rb:156:in `block in text'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/card.rb:52:in `yield'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/card.rb:52:in `use_cairo'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/graphics/text.rb:124:in `text'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/api/text.rb:60:in `block in text'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/args/card_range.rb:13:in `call'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/args/card_range.rb:13:in `block in each'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/args/card_range.rb:13:in `each'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/args/card_range.rb:13:in `each'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/api/text.rb:60:in `text'
from text_options.rb:77:in `block in <main>'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/deck.rb:75:in `instance_eval'
from C:/Users/x/Documents/ruby-2.1.5/lib/ruby/gems/2.1.0/bundler/gems/squib-19767c54c4cd/lib/squib/deck.rb:75:in `initialize'
from text_options.rb:11:in `new'
from text_options.rb:11:in `<main>'
```

**Comment by andymeneely** [comment] 2015-09-04 15:45
I don't have a fix for this yet, but here's a reproducing case:

```ruby
require 'squib'

Squib::Deck.new do
  text(str: "Hello :tool:", font: 'Sans Bold 72', stroke_width: 5) do |embed|
    embed.svg key: ':tool:', file: 'spanner.svg', width: 32, height: 32
  end

  save_png prefix: 'bug_103_'
end

```

**Comment by andymeneely** [comment] 2015-10-21 02:59
The plot thickens. It's directly related to our [old friend](https://github.com/andymeneely/squib/blob/master/lib/squib/graphics/text.rb#L74), the zero-sized character used in text embedding. Switching that line from 0 to 1 makes the above code work. 

I'm beginning to think that having a font size of 0 is a corner case that Pango never intended. It likely screws up their matrix math when converting to paths, and clearly messed things up here. I'm thinking it'll be ok to have the size be 1/1024s of a pixel - I'll look at my test cases though.

**Comment by andymeneely** [comment] 2015-10-21 03:13
Just for fun, here's a minimal example with just Pango and Cairo. I'm submitting this to their bug tracker and will do some more investigating. 

```ruby
require 'cairo'
require 'pango'

cxt = Cairo::Context.new(Cairo::ImageSurface.new(100,100))
layout = cxt.create_pango_layout
font = Pango::FontDescription.new('Sans Bold 36')
layout.font_description = font

# This markup gives us space to render an image in an arbitrary place in the text flow
layout.markup = 'x<span size="0">a<span letter_spacing="20000">a</span>a</span>y'

cxt.pango_layout_path(layout) # fails here

cxt.show_pango_layout layout
cxt.target.write_to_png('bug_103.png')
```

Also: switching to a font-size of 1 for all platforms won't work either. So we're stuck until we figure out a better way to create space in the flow of the paragraph.

**Comment by andymeneely** [comment] 2015-10-21 03:24
And for traceability, the Ruby+Pango bug is here: https://github.com/ruby-gnome2/ruby-gnome2/issues/603

**Comment by andymeneely** [comment] 2016-10-05 19:43
Since we've worked around this with the latest release, this code no longer fails for me. I'll reopen if someone speaks up.

**Closed by andymeneely** 2016-10-05 19:43 UTC
Labels: bug
