### ISSUE TITLE
card back support

### ISSUE THREAD

**Issue by andjd** [andymeneely/squib#133] opened 2016-01-15 19:30 UTC
Add the ability for cards to have card backs associated with them.  This will allow us to generate front and back pages that line up properly when using save_sheet.  Something like:
```
Squib::Deck.new cards:3 do
  backs Squib::Deck.new cards: 3 do
    ...
  end
  ...
end
```

If the "backs" deck is the same length as the main deck, backs[i] can be applied to card[i]. Otherwise, another method (`backs_index`?) can be used to map fronts to backs.

**Comment by bcompter** [comment] 2016-01-15 19:35
I'm guessing this is for home brew print and play right?  Could this not be done with careful placement of data in your csv/xls files?  First nine cards are fronts, then nine back, etc...

**Comment by andymeneely** [comment] 2016-01-16 13:28
This is a duplicate of #93. Please continue the discussion there.

**Closed by andymeneely** 2016-01-16 13:28 UTC
Labels: duplicate
